version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - 'apps/*'
      - 'packages/*'
    schedule:
      interval: 'weekly'
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
      - dependency-name: '@types/vscode'
        update-types: ['version-update:semver-minor']
